version: '3.9'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - postgres
        container_name: store_web
        ports:
            - "5000:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__StoreDbContext=User ID=postgres;Password=1234;Host=postgres;Port=5432;Database=storeDb;
    postgres:
        container_name: store_db
        image: postgres:latest
        environment:
            POSTGRES_DB: "storeDb"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - '0.0.0.0:5432:5432'

volumes:
    postgres-data: